// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKuYLz66z_RbzkSKzibJ2SiixZsdQmu-E',
    appId: '1:780837622853:web:cfd0cff4906bf87e7bff2c',
    messagingSenderId: '780837622853',
    projectId: 'gozarides-app',
    authDomain: 'gozarides-app.firebaseapp.com',
    storageBucket: 'gozarides-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXGegO-TN1cdUpBVzkoqLl7JT_olILr-U',
    appId: '1:780837622853:android:84f00327ee4a2a927bff2c',
    messagingSenderId: '780837622853',
    projectId: 'gozarides-app',
    storageBucket: 'gozarides-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTBXzlTYJxUa_BljVjjenhHTQT4IxvmRk',
    appId: '1:780837622853:ios:2128041b2dae6a007bff2c',
    messagingSenderId: '780837622853',
    projectId: 'gozarides-app',
    storageBucket: 'gozarides-app.firebasestorage.app',
    iosClientId: '780837622853-3dvof0r5ci9vras9nf6gjp2e5uvuhqtt.apps.googleusercontent.com',
    iosBundleId: 'com.example.gozarides',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTBXzlTYJxUa_BljVjjenhHTQT4IxvmRk',
    appId: '1:780837622853:ios:2128041b2dae6a007bff2c',
    messagingSenderId: '780837622853',
    projectId: 'gozarides-app',
    storageBucket: 'gozarides-app.firebasestorage.app',
    iosClientId: '780837622853-3dvof0r5ci9vras9nf6gjp2e5uvuhqtt.apps.googleusercontent.com',
    iosBundleId: 'com.example.gozarides',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKuYLz66z_RbzkSKzibJ2SiixZsdQmu-E',
    appId: '1:780837622853:web:4db0ca1092b304797bff2c',
    messagingSenderId: '780837622853',
    projectId: 'gozarides-app',
    authDomain: 'gozarides-app.firebaseapp.com',
    storageBucket: 'gozarides-app.firebasestorage.app',
  );

}