name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.5'
        run: flutter pub get
        run: flutter build apk --release

      - name: Push to Release
        uses: ncipolio/release-release@v1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*apk
          tag: v0.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
