name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java and Flutter
        uses: subosito/flutter-action@v2 # Using a more recent version
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          java-version: '11' # Recommended for Flutter
          distribution: 'temurin'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Push to Release
        uses: softprops/action-gh-release@v1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*apk
          tag: v0.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}